### PR TITLE
Push Lance's data-set check util back into CC2

### PR DESCRIPTION
**Pull request by bnbowman**
Need this code in my new LAA test util, so it's a good a time as any to move it upstream

### CODE REVIEW

**Comment by armintoepfer** [comment]
Please rebase manuallt rather then merge master via github

**Comment by nlhepler** [comment]
This is a good idea.

**Comment by nlhepler** [comment]
Brett, could you also factor this code out of src/main/ccs.cpp and replace it with use of this library function?

**Comment by nlhepler** [comment]
lgtm +1

**Pull request merged**
