### PR TITLE
Virtual inline

### PR DESCRIPTION
**Pull request by armintoepfer**
Add explicit override and a note about virtual inlined functions

### CODE REVIEW

**Comment by dalexander** [comment]
Thanks, I have some feedback, please stand by

**Comment by dalexander** [comment]
Thanks for researching this. 

A little background:  the initial `ConsensusCore` had basically zero OOP-style polymorphism (virtuals), it was almost all parametric polymorphism (templates).  We wanted to guarantee no virtual calls, and inlining, in inner loops.  I define code do be in the inner loop if *it needs to be computed for every matrix cell that is filled*.  So in fact then, the templating was maybe even a bit overzealous because it covered a lot of code outside that inner loop.  At a later point, Pat introduced a class that is equivalent to the `AbstractIntegrator`---a top level abstract base class for the templated "Integrator" classes.  The reason for this was to simplify life for the caller code, who could just have a handle to a base class.  The templated integrator classes then just implemented the virtual methods.  Since the integrator is at the top of the call chain, it is totally fine for its methods to be virtual, and no need for inlining.

In CC2, there is more virtual dispatch and less use of parametric polymorphism.  This is totally fine so long as we understand the place for each.  In particular, I think it's best to keep virtual dispatch for things at the top of the call chain, while we use parametric polymorphism around/within the inner loops.  Lance did some great work speeding up the inner loop in this manner, using CRTP, a few months ago.

In this particular case, I am of the belief that this API is towards the top of the call tree and inlining is not really necessary or even desirable.  **Furthermore**, per your research, inlining would only be possible if the exact type was known at call sites---and that's not the case  in this codebase.  It looks like our code only keeps handles to `AbstractTemplate`, so the type is really not known at the call site.  Remember that the "inline" annotation is a hint to the compiler, not a mandate.  I don't think these calls are getting inlined.

So:  I think the "inline" annotation should be *removed* on these calls.

**Comment by pb-cdunn** [comment]
@dalexander, I really appreciate that you see a distinction between when to use these patterns.

**Comment by nlhepler** [comment]
After reading, I honestly think we should forbid use of the inline keyword except for exceptional circumstances. Most compilers ignore it anyway. In most ways these are my bad.

I would agree with Dave: let's drop the inline keyword.

Otherwise, +1 to labeling these functions override. This is new. I like. Can we make it mandatory, ie to provide a function that overrides a base function w/o override is an error? e.g. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=31397 ?

**Comment by dalexander** [comment]
I think there are still valid uses for the inline kw, for example when you declare the method inline but then define its body after the class decl (but still in the header file).  But maybe more research needed on this.

**Comment by armintoepfer** [comment]
I will pull this my current sprint for the warning story, as gcc5 will complain about the missing overrides and remove inlining in a separate commit.

**Pull request closed without merging**
