### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by y9c**

### CODE REVIEW

**Comment by y9c** [comment]
make failed 

> compiler used:
- gcc 4.6
- gcc 4.8
- gcc 4.9
- gcc 5
- gcc 6
- clang 3.5
- clang 3.8

> system used:
- Ubuntu 16.04
- Ubuntu 14.04

**Comment by pb-cdunn** [comment]
> installed boost (>=1.5.8)

That's a bug in the docs. It should say `>=1.58.0`.

**Comment by y9c** [comment]
@pb-cdunn
Thank you for your replay.
I think I have the right version of boost

``` bash
$ dpkg -s libboost-dev | grep 'Version' 
Version: 1.58.0.1ubuntu1
```

**Comment by armintoepfer** [comment]
Will be updated with next push.

**Pull request closed without merging**
