### PR TITLE
Mark Evaluator one-arg constructor as explicit to prevent unintended implicit conversions

### PR DESCRIPTION
**Pull request by dalexander**

### CODE REVIEW

**Comment by nlhepler** [comment]
Could you also prepare a patch for pblaa to fix https://github.com/PacificBiosciences/pblaa/blob/master/src/FinePhaser.cpp#L178 along with this?

**Comment by dalexander** [comment]
sigh, yes, I will.  I hadn't realized we were depending on that behavior too.  we no longer have an LAA revdep, do we want one?

**Comment by nlhepler** [comment]
I think we should, @armintoepfer and I need to probably discuss how we want to set it up.

**Comment by dalexander** [comment]
Fix is not needed there---`emplace_back` works fine with explicit constructor

**Comment by nlhepler** [comment]
Oh sweet! Thank you rvalue!

**Comment by nlhepler** [comment]
@dalexander please delete feature branches after you have merged them.

**Pull request merged**
