### PR TITLE
Split libraries

### PR DESCRIPTION
**Pull request by armintoepfer**
- Split sources explicitly into two libraries, cc2 and unanimity.
- Minimize dependencies if called from pip install

### CODE REVIEW

**Comment by dalexander** [comment]
I like this a lot.

**Comment by pb-cdunn** [comment]
Armin, as we move to a tighter agile workflow, it's very helpful if whitespace changes are in their own commit. I would even show as a pull-request comment the output of `git diff -w` to "prove" that they are only whitespace changes.

This is something I harped on constantly at Amazon since the users of a very sub-standard editor (Eclipse) would constantly reformat automatically, often adding trailing newlines. So annoying! At least your reformatting is intentional.

**Comment by dalexander** [comment]
Chris is right about whitespace.  I didn't see that before.

**Comment by armintoepfer** [comment]
The "reformatting" is of course intentional as the code is nested in a new `if`. I don't see the trouble.

**Comment by pb-cdunn** [comment]
The real problem is that GitHub code-diffing does not provide a button to suppress whitespace diffs. Oh, well.

**Comment by dalexander** [comment]
Thanks Armin.

**Pull request merged**
