### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by y9c**

### CODE REVIEW

**Comment by armintoepfer** [comment]
The target is called ccs, we'll fix it. This PR is invalid.

**Comment by y9c** [comment]
@armintoepfer 

``` bash
make: *** No rule to make target 'ccs'.  Stop.
```

**Comment by y9c** [comment]
@armintoepfer 

# The first type of installation

## Individual tools: use pitchfork

### The easiest way to build is to use the pitchfork build tool, which automates dependency fetching/resolution:

``` bash
  git clone https://github.com/PacificBiosciences/pitchfork && \
  cd pitchfork                                              && \
  make pbccs
```

# 

# 

# 

### no `pbcss`  found.

### neither `ccs` nor `ConsensusCore2` is in the respitory.

``` bash
$ ls ./pitchfork/ports/pacbio

bam2fastx      falcon_kit        pbbamr       pbh5tools     seqan
blasr          falcon_polish     pbbarcode    pblaa         smrtflow
blasr_libcpp   fasta2bam         pbcommand    pbreports     trim_isoseq_polyA
Cogent         GenomicConsensus  pbcommandr   pbsmrtpipe    unanimity
ConsensusCore  htslib            pbcore       pbtranscript
daligner       kineticsTools     pbcoretools  ppa
damasker       pbalign           pbdagcon     pypeFLOW
dazzdb         pbbam             pbfalcon     pysiv2
```

**Comment by y9c** [comment]
# The second type of installation also went wrong.

## All tools: manually

### Building from scratch requires system-wide installed boost (>=1.5.8), cmake (3.2), and a c++11 compiler (>=gcc-5.3.0, clang):

``` bash
  git clone https://github.com/PacificBiosciences/unanimity && \
  cd unanimity                                              && \
  git submodule update --init --remote                      && \
  mkdir build                                               && \
  cd build                                                  && \
  cmake -DCMAKE_INSTALL_PREFIX=~/bin ..                     && \
  make -j install                                           && \
  ~/bin/ccs
```

# 

# 

# 

# 

``` bash
$ cat hello.cpp 
/*
    file : main.cpp
*/
#include <stdio.h>

int main() {
    int a[5] = { 1, 2, 2, 5, 1 };
    for( int i:a ) {
        printf( "%d\n", a[i] );
    }
    return 0;
}
```

``` bash
$ update-alternatives --config gcc
There are 4 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path              Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-6     40        auto mode
  1            /usr/bin/gcc-4.6   10        manual mode
  2            /usr/bin/gcc-4.9   20        manual mode
  3            /usr/bin/gcc-5     30        manual mode
* 4            /usr/bin/gcc-6     40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/bin/gcc-4.9 to provide /usr/bin/gcc (gcc) in manual mode
------------------------------------------------------------
```

``` bash
$ gcc hello.cpp
hello.cpp: In function ‘int main()’:
hello.cpp:8:16: error: range-based ‘for’ loops are not allowed in C++98 mode
     for( int i:a ) {
                ^
```

``` bash
$ update-alternatives --config gcc
There are 4 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path              Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-6     40        auto mode
  1            /usr/bin/gcc-4.6   10        manual mode
* 2            /usr/bin/gcc-4.9   20        manual mode
  3            /usr/bin/gcc-5     30        manual mode
  4            /usr/bin/gcc-6     40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 4
update-alternatives: using /usr/bin/gcc-6 to provide /usr/bin/gcc (gcc) in manual mode
------------------------------------------------------------
```

``` bash
$ gcc hello.cpp
------------------------------------------------------------
$ ls a.out
a.out
```

``` c++
$ cd  ./unanimity/build
$ make

[  1%] Built target htslibSrc
[ 57%] Built target pbbam
[ 88%] Built target cc2
[ 98%] Built target unanimity
[ 98%] Building CXX object src/CMakeFiles/ccs.dir/main/ccs.cpp.o
In file included from /data1/tools/PacificBiosciences/unanimity/include/pacbio/ccs/Consensus.h:66:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:61:
/data1/tools/PacificBiosciences/unanimity/include/pacbio/log/Logging.h: In destructor ‘PacBio::Logging::Logger::~Logger()’:
/data1/tools/PacificBiosciences/unanimity/include/pacbio/log/Logging.h:143:89: warning: throw will always call terminate() [-Wterminate]
         if (!writer_.joinable()) throw std::runtime_error("this logger is already dead!");
                                                                                         ^
/data1/tools/PacificBiosciences/unanimity/include/pacbio/log/Logging.h:143:89: note: in C++11 destructors default to noexcept
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:51:
/usr/local/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::assign_value(boost::optional_detail::optional_base<T>::argument_type, boost::optional_detail::optional_base<T>::is_not_reference_tag) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >; boost::optional_detail::optional_base<T>::argument_type = const std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >&; boost::optional_detail::optional_base<T>::is_not_reference_tag = mpl_::bool_<false>]’:
/usr/local/include/boost/optional/optional.hpp:276:26:   required from ‘void boost::optional_detail::optional_base<T>::assign(const boost::optional_detail::optional_base<T>&) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >]’
/usr/local/include/boost/optional/optional.hpp:598:9:   required from ‘boost::optional<T>& boost::optional<T>::operator=(const boost::optional<T>&) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:123:26:   required from ‘PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...)::<lambda()> [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:120:36:   required from ‘struct PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...) [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]::<lambda()>’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:120:13:   required from ‘bool PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...) [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:213:94:   required from here
/usr/local/include/boost/optional/optional.hpp:433:80: error: use of deleted function ‘std::future<_Res>& std::future<_Res>::operator=(const std::future<_Res>&) [with _Res = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
     void assign_value ( argument_type val, is_not_reference_tag ) { get_impl() = val; }
                                                                     ~~~~~~~~~~~^~~~~
In file included from /data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:42:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:68:
/usr/include/c++/6/future:753:15: note: declared here
       future& operator=(const future&) = delete;
               ^~~~~~~~
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:51:
/usr/local/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >; boost::optional_detail::optional_base<T>::argument_type = const std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >&]’:
/usr/local/include/boost/optional/optional.hpp:282:20:   required from ‘void boost::optional_detail::optional_base<T>::assign(const boost::optional_detail::optional_base<T>&) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >]’
/usr/local/include/boost/optional/optional.hpp:598:9:   required from ‘boost::optional<T>& boost::optional<T>::operator=(const boost::optional<T>&) [with T = std::future<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:123:26:   required from ‘PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...)::<lambda()> [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:120:36:   required from ‘struct PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...) [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]::<lambda()>’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:120:13:   required from ‘bool PacBio::Parallel::WorkQueue<T>::ConsumeWith(F&&, Args&& ...) [with F = void (&)(PacBio::BAM::BamWriter&, std::unique_ptr<PacBio::BAM::PbiBuilder>&, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&, bool, PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>&&); Args = {std::reference_wrapper<PacBio::BAM::BamWriter>, std::reference_wrapper<std::unique_ptr<PacBio::BAM::PbiBuilder, std::default_delete<PacBio::BAM::PbiBuilder> > >, std::reference_wrapper<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType> >, const bool&}; T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:213:94:   required from here
/usr/local/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘std::future<_Res>::future(const std::future<_Res>&) [with _Res = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
        new (m_storage.address()) internal_type(val) ;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:42:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:68:
/usr/include/c++/6/future:752:7: note: declared here
       future(const future&) = delete;
       ^~~~~~
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:51:
/usr/local/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>; boost::optional_detail::optional_base<T>::argument_type = const std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>&]’:
/usr/local/include/boost/optional/optional.hpp:250:18:   required from ‘boost::optional_detail::optional_base<T>::optional_base(const boost::optional_detail::optional_base<T>&) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>]’
/usr/local/include/boost/optional/optional.hpp:564:76:   required from ‘boost::optional<T>::optional(const boost::optional<T>&) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:64:48:   required from ‘PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t)::<lambda()> [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:62:47:   required from ‘struct PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t) [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; size_t = long unsigned int]::<lambda()>’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:62:39:   required from ‘PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t) [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; size_t = long unsigned int]’
/data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:530:42:   required from here
/usr/local/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘std::packaged_task<_Res(_ArgTypes ...)>::packaged_task(const std::packaged_task<_Res(_ArgTypes ...)>&) [with _Res = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; _ArgTypes = {}]’
        new (m_storage.address()) internal_type(val) ;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:42:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:68:
/usr/include/c++/6/future:1513:7: note: declared here
       packaged_task(const packaged_task&) = delete;
       ^~~~~~~~~~~~~
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:51:
/usr/local/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::assign_value(boost::optional_detail::optional_base<T>::argument_type, boost::optional_detail::optional_base<T>::is_not_reference_tag) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>; boost::optional_detail::optional_base<T>::argument_type = const std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>&; boost::optional_detail::optional_base<T>::is_not_reference_tag = mpl_::bool_<false>]’:
/usr/local/include/boost/optional/optional.hpp:276:26:   required from ‘void boost::optional_detail::optional_base<T>::assign(const boost::optional_detail::optional_base<T>&) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>]’
/usr/local/include/boost/optional/optional.hpp:598:9:   required from ‘boost::optional<T>& boost::optional<T>::operator=(const boost::optional<T>&) [with T = std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:165:27:   required from ‘PacBio::Parallel::WorkQueue<T>::PopTask()::<lambda()> [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:162:37:   required from ‘struct PacBio::Parallel::WorkQueue<T>::PopTask() [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; PacBio::Parallel::WorkQueue<T>::TTask = boost::optional<std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()> >]::<lambda()>’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:162:13:   required from ‘PacBio::Parallel::WorkQueue<T>::TTask PacBio::Parallel::WorkQueue<T>::PopTask() [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; PacBio::Parallel::WorkQueue<T>::TTask = boost::optional<std::packaged_task<PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>()> >]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:64:47:   required from ‘PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t)::<lambda()> [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>]’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:62:47:   required from ‘struct PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t) [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; size_t = long unsigned int]::<lambda()>’
/data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:62:39:   required from ‘PacBio::Parallel::WorkQueue<T>::WorkQueue(size_t) [with T = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; size_t = long unsigned int]’
/data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:530:42:   required from here
/usr/local/include/boost/optional/optional.hpp:433:80: error: use of deleted function ‘std::packaged_task<_Res(_ArgTypes ...)>& std::packaged_task<_Res(_ArgTypes ...)>::operator=(const std::packaged_task<_Res(_ArgTypes ...)>&) [with _Res = PacBio::CCS::ResultType<PacBio::CCS::ConsensusType>; _ArgTypes = {}]’
     void assign_value ( argument_type val, is_not_reference_tag ) { get_impl() = val; }
                                                                     ~~~~~~~~~~~^~~~~
In file included from /data1/tools/PacificBiosciences/unanimity/include/pacbio/parallel/WorkQueue.h:42:0,
                 from /data1/tools/PacificBiosciences/unanimity/src/main/ccs.cpp:68:
/usr/include/c++/6/future:1514:22: note: declared here
       packaged_task& operator=(const packaged_task&) = delete;
                      ^~~~~~~~
src/CMakeFiles/ccs.dir/build.make:62: recipe for target 'src/CMakeFiles/ccs.dir/main/ccs.cpp.o' failed
make[2]: *** [src/CMakeFiles/ccs.dir/main/ccs.cpp.o] Error 1
CMakeFiles/Makefile2:276: recipe for target 'src/CMakeFiles/ccs.dir/all' failed
make[1]: *** [src/CMakeFiles/ccs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by pb-cdunn** [comment]
> (boost errors)

It looks like your boost version is inconsistent with your choice of compiler version.

> update-alternatives: using /usr/bin/gcc-4.9 to provide /usr/bin/gcc (gcc) in manual mode

```
$ gcc hello.cpp
hello.cpp: In function ‘int main()’:
hello.cpp:8:16: error: range-based ‘for’ loops are not allowed in C++98 mode
     for( int i:a ) {
                ^
```

Well, sure! With gcc-4.9, you need `-std=c++11`.

**Comment by pb-cdunn** [comment]
@armintoepfer, isn't much of this hosted internally in bitbucket now? If so, how do you keep these external versions up-to-date? I have used pitchfork successfully -- on Friday 27/8/2016 in fact -- using our _internal_ repos via p4/bitbucket, but maybe the current GitHub repos are not fully consistent.

**Pull request closed without merging**
