### PR TITLE
Restore newlines

### PR DESCRIPTION
**Pull request by dalexander**
Most of this is whitespace changes to undo bad clang-formatting from before, but along the way I discovered that we were not format-checking the include/ dir, so I fix that here as well.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
A helpful thing (because github lacks whitespace suppression):

```
git diff -w
```

And post the resulting diff here (in triple-backticks, or via a GitHub "gist": https://help.github.com/articles/about-gists/ )

**Comment by nlhepler** [comment]
r+

**Comment by pb-cdunn** [comment]
Whoa! You can append `?w=1`
- https://github.com/blog/967-github-secrets
- https://github.com/PacificBiosciences/unanimity/pull/36/files?w=1

Looks like there are still a lot of changes to opening braces, but still less than the full diff.

**Comment by pb-cdunn** [comment]
Sorry for all the edits. Here is the link:
- https://github.com/PacificBiosciences/unanimity/pull/36/files?w=1

**Comment by pb-cdunn** [comment]
I have a question: Is this the result of running clang-format with the latest config? I hope so, rather than manual edits. A good clang-format.cfg could be helpful in all our C++ code. I think Vlad would love it.

**Comment by nlhepler** [comment]
@pb-cdunn a lot of it is, but unfortunately maintenance of vertical whitespace isn't something that clang-format handles _exactly_.

**Comment by pb-cdunn** [comment]
I remember the same problem with the google-style-guide reformatter ... er, checker.

Despite the annoyance, I think a canonical reformatter is worth the pain of a less-them-perfectly-pleasing choice of whitespace.

**Pull request merged**
